(() => {
  let canvas, ctx, painting=false, last=null, color='#e9578a', size=8, tool='brush';
  let strokes=[], ready=false, applyingRemote=false, saved=[];
  const $=id=>document.getElementById(id);
  const esc=v=>{const d=document.createElement('div');d.textContent=v||'';return d.innerHTML};
  function point(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*canvas.width/r.width,y:(e.clientY-r.top)*canvas.height/r.height};}
  function paintStroke(s){if(!s?.points?.length)return;ctx.save();ctx.strokeStyle=s.tool==='eraser'?'#fff':s.color;ctx.fillStyle=ctx.strokeStyle;ctx.lineWidth=s.size;ctx.lineCap='round';ctx.lineJoin='round';if(s.points.length===1){ctx.beginPath();ctx.arc(s.points[0].x,s.points[0].y,s.size/2,0,Math.PI*2);ctx.fill()}else{ctx.beginPath();ctx.moveTo(s.points[0].x,s.points[0].y);for(let i=1;i<s.points.length;i++)ctx.lineTo(s.points[i].x,s.points[i].y);ctx.stroke()}ctx.restore()}
  function redraw(){ctx.clearRect(0,0,canvas.width,canvas.height);strokes.forEach(paintStroke)}
  async function sync(){if(!db||applyingRemote)return;try{await db.ref('drawing/shared').set({strokes,updatedAt:Date.now()})}catch(e){console.error('Dibujo:',e)}}
  function start(e){e.preventDefault();painting=true;last=point(e);const s={color,size,tool,points:[last]};strokes.push(s);paintStroke(s);canvas.setPointerCapture?.(e.pointerId)}
  function move(e){if(!painting)return;e.preventDefault();const p=point(e),s=strokes[strokes.length-1];s.points.push(p);ctx.save();ctx.strokeStyle=s.tool==='eraser'?'#fff':s.color;ctx.lineWidth=s.size;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();ctx.moveTo(last.x,last.y);ctx.lineTo(p.x,p.y);ctx.stroke();ctx.restore();last=p}
  async function end(e){if(!painting)return;e?.preventDefault();painting=false;last=null;await sync()}
  function snapshot(){const copy=document.createElement('canvas');copy.width=canvas.width;copy.height=canvas.height;const c=copy.getContext('2d');c.fillStyle='#fff';c.fillRect(0,0,copy.width,copy.height);for(const s of strokes){c.save();c.strokeStyle=s.tool==='eraser'?'#fff':s.color;c.fillStyle=c.strokeStyle;c.lineWidth=s.size;c.lineCap='round';c.lineJoin='round';if(s.points.length===1){c.beginPath();c.arc(s.points[0].x,s.points[0].y,s.size/2,0,Math.PI*2);c.fill()}else{c.beginPath();c.moveTo(s.points[0].x,s.points[0].y);for(let i=1;i<s.points.length;i++)c.lineTo(s.points[i].x,s.points[i].y);c.stroke()}c.restore()}return copy.toDataURL('image/png')}
  function renderSaved(){const g=$('savedDrawings');const empty=$('emptyDrawings');const count=$('drawingCount');if(!g)return;g.innerHTML='';count.textContent=`${saved.length} ${saved.length===1?'dibujo':'dibujos'}`;empty.style.display=saved.length?'none':'block';[...saved].sort((a,b)=>b.createdAt-a.createdAt).forEach(d=>{const card=document.createElement('article');card.className='drawing-card';card.innerHTML=`<img src="${d.image}" alt="${esc(d.name)}"><div class="drawing-card-body"><h3>🎨 ${esc(d.name)}</h3><small>📅 ${new Date(d.createdAt).toLocaleDateString('es-PE',{day:'numeric',month:'long',year:'numeric'})}</small><div class="drawing-card-actions"><button class="open-drawing">✏️ Abrir</button><button class="download-saved">⬇️ Descargar</button><button class="remove-saved">🗑️ Eliminar</button></div></div>`;card.querySelector('.open-drawing').onclick=()=>{strokes=Array.isArray(d.strokes)?d.strokes:[];redraw();sync();window.scrollTo({top:document.getElementById('drawingSection').offsetTop,behavior:'smooth'})};card.querySelector('.download-saved').onclick=()=>{const a=document.createElement('a');a.download=(d.name||'nuestro-dibujo').replace(/[^a-z0-9áéíóúñ _-]/gi,'')+'.png';a.href=d.image;a.click()};card.querySelector('.remove-saved').onclick=async()=>{if(!confirm('¿Eliminar este dibujo guardado?'))return;saved=saved.filter(x=>x.id!==d.id);await saveSaved();renderSaved()};g.appendChild(card)})}
  async function saveSaved(){if(!db)return;try{await db.ref('drawing/saved').set(saved)}catch(e){console.error('Dibujos guardados:',e)}}
  async function saveDrawing(){if(!strokes.length)return alert('Primero dibuja algo ❤️');const name=($('drawingName').value.trim()||'Nuestro dibujo');const item={id:Date.now(),name,createdAt:Date.now(),image:snapshot(),strokes:JSON.parse(JSON.stringify(strokes))};saved.push(item);await saveSaved();renderSaved();$('drawingName').value='';alert('🎨 Dibujo guardado en Dibujos hechos ❤️')}
  function setup(){if(ready||!$('drawingSection')||typeof db==='undefined'||!db)return;ready=true;canvas=$('drawingCanvas');ctx=canvas.getContext('2d');canvas.width=900;canvas.height=560;canvas.style.touchAction='none';canvas.addEventListener('pointerdown',start);canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerup',end);canvas.addEventListener('pointercancel',end);$('brushColor').oninput=e=>color=e.target.value;$('brushSize').oninput=e=>{size=+e.target.value;$('brushSizeValue').textContent=size};$('brushBtn').onclick=()=>{tool='brush';$('brushBtn').classList.add('active');$('eraserBtn').classList.remove('active')};$('eraserBtn').onclick=()=>{tool='eraser';$('eraserBtn').classList.add('active');$('brushBtn').classList.remove('active')};$('drawingUndo').onclick=async()=>{strokes.pop();redraw();await sync()};$('drawingClear').onclick=async()=>{if(!confirm('¿Borrar todo el dibujo para los dos?'))return;strokes=[];redraw();await sync()};$('drawingDownload').onclick=()=>{const a=document.createElement('a');a.download='nuestro-dibujo.png';a.href=snapshot();a.click()};$('saveDrawing').onclick=saveDrawing;db.ref('drawing/shared').on('value',snap=>{const v=snap.val();if(!v)return;applyingRemote=true;strokes=Array.isArray(v.strokes)?v.strokes:[];redraw();applyingRemote=false});db.ref('drawing/saved').on('value',snap=>{const v=snap.val();saved=Array.isArray(v)?v:Object.values(v||{});renderSaved()});redraw();renderSaved()}
  const wait=setInterval(()=>{try{setup()}catch(e){console.error(e)}if(ready)clearInterval(wait)},400);
})();