const firebaseConfig={apiKey:"AIzaSyBQ715-AtvVquF68tiqoSfyt3UZmejIo44",authDomain:"ciclo-a8187.firebaseapp.com",databaseURL:"https://ciclo-a8187-default-rtdb.firebaseio.com",projectId:"ciclo-a8187",storageBucket:"ciclo-a8187.firebasestorage.app",messagingSenderId:"418245025071",appId:"1:418245025071:web:dfa24fbaf23110416995da"};
let currentDate=new Date(),selectedProtection="",cloudReady=false,db=null;
const defaults={periodDate:"",periodLength:5,cycleLength:28,relations:[],memories:[],dates:[]};
let data=JSON.parse(localStorage.getItem("loveCalendar")||"null")||{};data={...defaults,...data,relations:data.relations||[],memories:data.memories||[],dates:data.dates||[]};
const $=id=>document.getElementById(id);const calendar=$("calendar"),monthTitle=$("monthTitle"),periodDateInput=$("periodDate"),periodLengthInput=$("periodLength"),cycleLengthInput=$("cycleLength"),relationDateInput=$("relationDate");
const fmt=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;const pretty=s=>s?new Date(s+"T12:00:00").toLocaleDateString("es-PE",{day:"numeric",month:"long",year:"numeric"}):"--";const add=(d,n)=>{let x=new Date(d);x.setDate(x.getDate()+n);return x};
function local(){localStorage.setItem("loveCalendar",JSON.stringify(data))}
async function saveCloud(){if(!cloudReady)return;try{await db.ref("shared").set(data)}catch(e){console.error(e)}}
function showSection(id){["calendarSection","datesSection","memoriesSection"].forEach(x=>$(x)?.classList.add("hidden"));$(id)?.classList.remove("hidden");if(id==="datesSection")renderDates();if(id==="memoriesSection")loadMemories()}
function selectProtection(t){selectedProtection=t;$("protectedBtn").classList.toggle("selected",t==="protected");$("unprotectedBtn").classList.toggle("selected",t==="unprotected")}
function calculate(){if(!data.periodDate){$("nextPeriod").textContent=$("ovulationDate").textContent=$("fertileDates").textContent="--";return}let p=new Date(data.periodDate+"T12:00:00"),n=add(p,+data.cycleLength),o=add(n,-14),a=add(o,-5),b=add(o,1);$("nextPeriod").textContent=pretty(fmt(n));$("ovulationDate").textContent=pretty(fmt(o));$("fertileDates").textContent=`${pretty(fmt(a))} - ${pretty(fmt(b))}`;$("cycleInfo").textContent=data.cycleLength}
function renderCalendar(){calendar.innerHTML="";let y=currentDate.getFullYear(),m=currentDate.getMonth(),first=new Date(y,m,1),last=new Date(y,m+1,0),start=first.getDay()||7;monthTitle.textContent=currentDate.toLocaleDateString("es-PE",{month:"long",year:"numeric"});for(let i=1;i<start;i++){let e=document.createElement("div");e.className="day empty";calendar.appendChild(e)}for(let d=1;d<=last.getDate();d++){let date=new Date(y,m,d),s=fmt(date),el=document.createElement("div");el.className="day";if(s===fmt(new Date))el.classList.add("today");let num=document.createElement("div");num.className="day-number";num.textContent=d;el.appendChild(num);if(data.periodDate){let p=new Date(data.periodDate+"T12:00:00"),pe=add(p,+data.periodLength-1),n=add(p,+data.cycleLength),o=add(n,-14),fs=add(o,-5),fe=add(o,1);if(date>=p&&date<=pe)el.classList.add("period");if(date>=fs&&date<=fe)el.classList.add("fertile");if(s===fmt(o)){el.classList.remove("fertile");el.classList.add("ovulation")}}let rs=data.relations.filter(r=>r.date===s);if(rs.length){let h=document.createElement("div");h.className="relation-heart";h.textContent=rs.some(r=>r.protection==="unprotected")?"❤️":"🛡️";el.appendChild(h)}el.onclick=()=>relationDateInput.value=s;calendar.appendChild(el)}}
function renderRelations(){let list=$("relationsList");list.innerHTML="";[...data.relations].sort((a,b)=>b.date.localeCompare(a.date)).forEach(r=>{let item=document.createElement("div");item.className="relation-item";item.innerHTML=`<div class="relation-info"><strong>${r.protection==="protected"?"🛡️":"❤️"} ${pretty(r.date)}</strong><small>${r.protection==="protected"?"Con protección":"Sin protección"}</small></div><button class="remove-relation">Eliminar</button>`;item.querySelector("button").onclick=async()=>{data.relations=data.relations.filter(x=>x.id!==r.id);local();await saveCloud();renderRelations();renderCalendar();update()};list.appendChild(item)})}
function update(){$("relationCount").textContent=data.relations.length;$ ("cycleInfo").textContent=data.cycleLength;calculate()}
$("calculateBtn").onclick=async()=>{if(!periodDateInput.value)return alert("Selecciona el primer día del periodo.");data.periodDate=periodDateInput.value;data.periodLength=+periodLengthInput.value;data.cycleLength=+cycleLengthInput.value;local();await saveCloud();calculate();renderCalendar();alert(cloudReady?"💕 Ciclo sincronizado":"💕 Guardado localmente")};
$("addRelation").onclick=async()=>{if(!relationDateInput.value)return alert("Selecciona una fecha.");if(!selectedProtection)return alert("Selecciona con o sin protección.");data.relations.push({id:Date.now(),date:relationDateInput.value,protection:selectedProtection});local();await saveCloud();selectedProtection="";$("protectedBtn").classList.remove("selected");$("unprotectedBtn").classList.remove("selected");renderRelations();renderCalendar();update()};
$("prevMonth").onclick=()=>{currentDate.setMonth(currentDate.getMonth()-1);renderCalendar()};$("nextMonth").onclick=()=>{currentDate.setMonth(currentDate.getMonth()+1);renderCalendar()};
$("clearData").onclick=async()=>{if(!confirm("¿Seguro que quieres borrar los datos del calendario?"))return;data.periodDate="";data.periodLength=5;data.cycleLength=28;data.relations=[];local();await saveCloud();periodDateInput.value="";periodLengthInput.value=5;cycleLengthInput.value=28;renderRelations();renderCalendar();update()};
function esc(v){let d=document.createElement("div");d.textContent=v||"";return d.innerHTML}
function renderDates(){let list=$("datesList"),empty=$("emptyDates"),count=$("dateCount");if(!list)return;list.innerHTML="";let arr=[...data.dates].sort((a,b)=>(a.date+"T"+(a.time||"")).localeCompare(b.date+"T"+(b.time||"")));count.textContent=`${arr.length} ${arr.length===1?"cita":"citas"}`;empty.style.display=arr.length?"none":"block";arr.forEach(c=>{let el=document.createElement("article");el.className="panel";el.style.marginTop="15px";el.innerHTML=`<h3>💕 ${esc(c.title)}</h3><p>📅 ${pretty(c.date)} · 🕐 ${esc(c.time||"Sin hora")}</p><p>📍 ${esc(c.place||"Sin lugar")}</p><p>${esc(c.description||"")}</p><button class="delete-btn">🗑️ Eliminar</button>`;el.querySelector("button").onclick=async()=>{if(!confirm("¿Eliminar esta cita?"))return;data.dates=data.dates.filter(x=>x.id!==c.id);local();await saveCloud();renderDates()};list.appendChild(el)})}
$("saveDate").onclick=async()=>{let title=$("dateTitle").value.trim(),date=$("dateDate").value,time=$("dateTime").value,place=$("datePlace").value.trim(),description=$("dateDescription").value.trim();if(!title||!date)return alert("Escribe al menos el título y la fecha.");data.dates.push({id:Date.now(),title,date,time,place,description});local();await saveCloud();["dateTitle","dateDate","dateTime","datePlace","dateDescription"].forEach(id=>$(id).value="");renderDates();alert(cloudReady?"💕 Cita guardada y sincronizada":"💕 Cita guardada localmente")};
function loadMemories(){let g=$("memoriesGallery"),empty=$("emptyMemories"),count=$("memoryCount");if(!g)return;g.innerHTML="";let ms=[...data.memories].sort((a,b)=>(b.date||"").localeCompare(a.date||""));count.textContent=`${ms.length} ${ms.length===1?"recuerdo":"recuerdos"}`;empty.style.display=ms.length?"none":"block";ms.forEach(m=>{let c=document.createElement("article");c.className="memory-card";c.innerHTML=`<img src="${m.imageUrl||m.imageData||""}" alt="${esc(m.title)}"><div class="memory-content"><h3>${esc(m.title)}</h3><small>📅 ${pretty(m.date)}</small><p>${esc(m.description)}</p></div>`;g.appendChild(c)})}
async function init(){periodDateInput.value=data.periodDate||"";periodLengthInput.value=data.periodLength||5;cycleLengthInput.value=data.cycleLength||28;renderCalendar();renderRelations();renderDates();loadMemories();if(typeof firebase==="undefined")return;try{firebase.initializeApp(firebaseConfig);db=firebase.database();cloudReady=true;const ref=db.ref("shared");const snap=await ref.once("value");if(snap.exists()){data={...defaults,...snap.val(),relations:(snap.val().relations||[]),memories:(snap.val().memories||[]),dates:(snap.val().dates||[])};local();periodDateInput.value=data.periodDate||"";periodLengthInput.value=data.periodLength||5;cycleLengthInput.value=data.cycleLength||28;renderCalendar();renderRelations();renderDates();loadMemories();}else await saveCloud();ref.on("value",s=>{if(!s.exists())return;let incoming=s.val();data={...defaults,...incoming,relations:incoming.relations||[],memories:incoming.memories||[],dates:incoming.dates||[]};local();periodDateInput.value=data.periodDate||"";periodLengthInput.value=data.periodLength||5;cycleLengthInput.value=data.cycleLength||28;renderCalendar();renderRelations();renderDates();loadMemories()})}catch(e){console.error("Firebase:",e);cloudReady=false}}
(function loadFirebase(){let urls=["https://www.gstatic.com/firebasejs/10.12.2/firebase-app-compat.js","https://www.gstatic.com/firebasejs/10.12.2/firebase-database-compat.js"];let i=0;function next(){if(i>=urls.length)return init();let s=document.createElement("script");s.src=urls[i++];s.onload=next;s.onerror=()=>console.error("No se pudo cargar Firebase");document.head.appendChild(s)}next()})();