/* NUESTRO ESPACIO - datos sincronizados con Firebase Realtime Database */
const firebaseConfig={apiKey:"AIzaSyBQ715-AtvVquF68tiqoSfyt3UZmejIo44",authDomain:"ciclo-a8187.firebaseapp.com",databaseURL:"https://ciclo-a8187-default-rtdb.firebaseio.com",projectId:"ciclo-a8187",storageBucket:"ciclo-a8187.firebasestorage.app",messagingSenderId:"418245025071",appId:"1:418245025071:web:dfa24fbaf23110416995da"};
let currentDate=new Date(),selectedProtection="",cloudReady=false,db=null;
const defaults={periodDate:"",periodLength:5,cycleLength:28,relations:[],memories:[]};
let data=JSON.parse(localStorage.getItem("loveCalendar")||"null")||structuredClone(defaults);data.memories=data.memories||[];
const $=id=>document.getElementById(id),calendar=$("calendar"),monthTitle=$("monthTitle"),periodDateInput=$("periodDate"),periodLengthInput=$("periodLength"),cycleLengthInput=$("cycleLength"),relationDateInput=$("relationDate");
const fmt=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
const pretty=s=>s?new Date(s+"T12:00:00").toLocaleDateString("es-PE",{day:"numeric",month:"long",year:"numeric"}):"--";
const add=(d,n)=>{let x=new Date(d);x.setDate(x.getDate()+n);return x};
function local(){localStorage.setItem("loveCalendar",JSON.stringify(data))}
async function cloud(){if(!cloudReady)return;try{await db.ref("couples/shared").set({periodDate:data.periodDate,periodLength:data.periodLength,cycleLength:data.cycleLength,relations:data.relations||[],memories:data.memories||[]})}catch(e){console.error("Firebase Realtime Database:",e)}}
function showSection(id){$("calendarSection").classList.add("hidden");$("memoriesSection").classList.add("hidden");$(id).classList.remove("hidden");if(id==="memoriesSection")loadMemories()}
function selectProtection(t){selectedProtection=t;$("protectedBtn").classList.toggle("selected",t==="protected");$("unprotectedBtn").classList.toggle("selected",t==="unprotected")}
function calculate(){if(!data.periodDate){$("nextPeriod").textContent=$("ovulationDate").textContent=$("fertileDates").textContent="--";return}let p=new Date(data.periodDate+"T12:00:00"),n=add(p,+data.cycleLength),o=add(n,-14),a=add(o,-5),b=add(o,1);$("nextPeriod").textContent=pretty(fmt(n));$("ovulationDate").textContent=pretty(fmt(o));$("fertileDates").textContent=`${pretty(fmt(a))} - ${pretty(fmt(b))}`;$("cycleInfo").textContent=data.cycleLength}
function renderCalendar(){calendar.innerHTML="";let y=currentDate.getFullYear(),m=currentDate.getMonth(),first=new Date(y,m,1),last=new Date(y,m+1,0),start=first.getDay()||7;let mn=currentDate.toLocaleDateString("es-PE",{month:"long",year:"numeric"});monthTitle.textContent=mn.charAt(0).toUpperCase()+mn.slice(1);for(let i=1;i<start;i++){let e=document.createElement("div");e.className="day empty";calendar.appendChild(e)}for(let d=1;d<=last.getDate();d++){let date=new Date(y,m,d),s=fmt(date),el=document.createElement("div");el.className="day";if(s===fmt(new Date))el.classList.add("today");let num=document.createElement("div");num.className="day-number";num.textContent=d;el.appendChild(num);if(data.periodDate){let p=new Date(data.periodDate+"T12:00:00"),pe=add(p,+data.periodLength-1),n=add(p,+data.cycleLength),o=add(n,-14),fs=add(o,-5),fe=add(o,1);if(date>=p&&date<=pe)el.classList.add("period");if(date>=fs&&date<=fe)el.classList.add("fertile");if(s===fmt(o)){el.classList.remove("fertile");el.classList.add("ovulation")}}let rs=data.relations.filter(r=>r.date===s);if(rs.length){el.classList.add("relation-day");let h=document.createElement("div");h.className="relation-heart";h.textContent=rs.some(r=>r.protection==="unprotected")?"❤️":"🛡️";el.appendChild(h)}el.onclick=()=>relationDateInput.value=s;calendar.appendChild(el)}}
function renderRelations(){let list=$("relationsList");list.innerHTML="";[...data.relations].sort((a,b)=>new Date(b.date)-new Date(a.date)).forEach(r=>{let item=document.createElement("div");item.className="relation-item";let info=document.createElement("div");info.className="relation-info";info.innerHTML=`<strong>${r.protection==="protected"?"🛡️":"❤️"} ${pretty(r.date)}</strong><small>${r.protection==="protected"?"Con protección":"Sin protección"}</small>`;let del=document.createElement("button");del.className="remove-relation";del.textContent="Eliminar";del.onclick=async()=>{data.relations=data.relations.filter(x=>x.id!==r.id);local();await cloud();renderRelations();renderCalendar();update()};item.append(info,del);list.appendChild(item)})}
function update(){$("relationCount").textContent=data.relations.length;$("cycleInfo").textContent=data.cycleLength;calculate()}
$("calculateBtn").onclick=async()=>{if(!periodDateInput.value)return alert("Selecciona el primer día del periodo.");data.periodDate=periodDateInput.value;data.periodLength=+periodLengthInput.value;data.cycleLength=+cycleLengthInput.value;local();await cloud();calculate();renderCalendar();alert(cloudReady?"💕 Ciclo sincronizado":"💕 Guardado en este dispositivo")};
$("addRelation").onclick=async()=>{if(!relationDateInput.value)return alert("Selecciona una fecha.");if(!selectedProtection)return alert("Selecciona con o sin protección.");data.relations.push({id:Date.now(),date:relationDateInput.value,protection:selectedProtection});local();await cloud();selectedProtection="";$("protectedBtn").classList.remove("selected");$("unprotectedBtn").classList.remove("selected");renderRelations();renderCalendar();update();alert(cloudReady?"❤️ Guardado en la nube":"❤️ Guardado en este dispositivo")};
$("prevMonth").onclick=()=>{currentDate.setMonth(currentDate.getMonth()-1);renderCalendar()};$("nextMonth").onclick=()=>{currentDate.setMonth(currentDate.getMonth()+1);renderCalendar()};
$("clearData").onclick=async()=>{if(!confirm("¿Seguro que quieres borrar los datos del calendario?"))return;data={...defaults};local();await cloud();periodDateInput.value="";periodLengthInput.value=5;cycleLengthInput.value=28;renderRelations();renderCalendar();update()};
function esc(v){let d=document.createElement("div");d.textContent=v||"";return d.innerHTML}
function loadMemories(){let g=$("memoriesGallery"),empty=$("emptyMemories"),count=$("memoryCount");if(!g||!empty||!count)return;g.innerHTML="";let ms=[...(data.memories||[])].sort((a,b)=>new Date(b.date)-new Date(a.date));count.textContent=`${ms.length} ${ms.length===1?"recuerdo":"recuerdos"}`;empty.style.display=ms.length?"none":"block";ms.forEach(m=>{let c=document.createElement("article");c.className="memory-card";c.innerHTML=`<img src="${m.imageUrl||m.imageData||""}" alt="${esc(m.title)}" loading="lazy"><div class="memory-content"><h3>${esc(m.title)}</h3><small>📅 ${pretty(m.date)}</small><p>${esc(m.description)}</p></div>`;g.appendChild(c)})}
function init(){periodDateInput.value=data.periodDate||"";periodLengthInput.value=data.periodLength||5;cycleLengthInput.value=data.cycleLength||28;renderCalendar();renderRelations();update();loadMemories();if(typeof firebase==="undefined")return;try{firebase.initializeApp(firebaseConfig);db=firebase.database();cloudReady=true;db.ref("couples/shared").once("value").then(s=>{if(s.exists()){data={...defaults,...data,...s.val()};data.relations=data.relations||[];data.memories=data.memories||[];local();periodDateInput.value=data.periodDate||"";periodLengthInput.value=data.periodLength||5;cycleLengthInput.value=data.cycleLength||28;renderCalendar();renderRelations();update();loadMemories()}}).catch(e=>{console.error(e);cloudReady=false})}catch(e){console.error(e)}}
(function loadFirebase(){let urls=["https://www.gstatic.com/firebasejs/10.12.2/firebase-app-compat.js","https://www.gstatic.com/firebasejs/10.12.2/firebase-database-compat.js"];let i=0;function next(){if(i>=urls.length)return init();let s=document.createElement("script");s.src=urls[i++];s.onload=next;s.onerror=()=>console.error("No se pudo cargar Firebase");document.head.appendChild(s)}next()})();